version: '3.4'
services:
  atlassian-connect:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - 'SECURITY_LOGIN=user'
      - 'SECURITY_PASSWWORD=password'
      - 'BASE_URL=http://localhost'
      - 'SERVER_PORT=8080'
